// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCtK0QiwC9sH_bLtPiyBPmPyaptiu9eQ0',
    appId: '1:859645554932:web:7b0efdf5706ceb8531aea1',
    messagingSenderId: '859645554932',
    projectId: 'truck-tracking-74d58',
    authDomain: 'truck-tracking-74d58.firebaseapp.com',
    storageBucket: 'truck-tracking-74d58.appspot.com',
    measurementId: 'G-RDTV05X1VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBAzrGr18XqXbkSUZdMUC03Qzp56dldOg',
    appId: '1:859645554932:android:c51a1207e91d589c31aea1',
    messagingSenderId: '859645554932',
    projectId: 'truck-tracking-74d58',
    storageBucket: 'truck-tracking-74d58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLN0AjMT1zYu7qN5awoHl97A9dczwv7ao',
    appId: '1:859645554932:ios:8db566e586accad131aea1',
    messagingSenderId: '859645554932',
    projectId: 'truck-tracking-74d58',
    storageBucket: 'truck-tracking-74d58.appspot.com',
    iosBundleId: 'com.shamiit.truckTracking',
  );
}
