
name: "Build Pipeline"
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Manually run this workflow
  
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.6

      - name: Build web
        run: flutter build web --release

      - run: dart --version
      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter test

      - run: flutter build apk --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.CODE_ACCESS_TOKEN_TT }}



