
name: "Build & Release Pipelines"
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Manually run this workflow
  
jobs:
  TEST-BUILD:
    name: RUNNING TESTING
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.5'
      - run: flutter upgrade
      - run: flutter test
      - name: Flutter doctor
        run: flutter doctor # this is an optional step and can be removed
      
  ANDROID-BUILD-DEPLOY:
    name: Build & Release Android APP
    runs-on: ubuntu-latest
    environment: DEV
    needs: TEST-BUILD
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.5'
      - run: flutter upgrade

      - run: flutter pub get
      - run: flutter test

      - run: flutter build apk --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.CODE_ACCESS_TOKEN_TT }}

  WEB-BUILD-DEPLOY:
    name: Build & Release Web
    runs-on: ubuntu-latest
    environment: DEV
    needs: TEST-BUILD
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.5'
      - run: flutter upgrade

      - run: flutter pub get
      
      - name: Build web
        run: flutter build web --release
    
      - name: 📂 Sync files and Release
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/web/
          exclude: |
            **/.git*
            **/.git*/**




